export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'


export const PRODUCT_Details_REQUEST = 'PRODUCT_Details_REQUEST'
export const PRODUCT_Details_SUCCESS = 'PRODUCT_Details_SUCCESS'
export const PRODUCT_Details_FAIL = 'PRODUCT_Details_FAIL'
